// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SampleWebApi.Repository;

#nullable disable

namespace SampleWebApi.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_Iquirium.Models.FeedbackProduto", b =>
                {
                    b.Property<int>("IdFeedbackProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFeedbackProduto"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("DataEnvio")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTipoFeedbackProduto")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioEnvio")
                        .HasColumnType("integer");

                    b.HasKey("IdFeedbackProduto");

                    b.HasIndex("IdTipoFeedbackProduto")
                        .IsUnique();

                    b.ToTable("tblFeedbackProduto", (string)null);
                });

            modelBuilder.Entity("API_Iquirium.Models.TipoFeedbackProduto", b =>
                {
                    b.Property<int>("IdTipoFeedbackProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoFeedbackProduto"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("IdTipoFeedbackProduto");

                    b.ToTable("tblTipoFeedbackProduto", (string)null);
                });

            modelBuilder.Entity("API_Iquirium.Models.FeedbackProduto", b =>
                {
                    b.HasOne("API_Iquirium.Models.TipoFeedbackProduto", null)
                        .WithOne()
                        .HasForeignKey("API_Iquirium.Models.FeedbackProduto", "IdTipoFeedbackProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
