name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
      - branch-**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0 # ou outra versão usada pelo projeto

      # Instalar dependências
      - name: Install dependencies
        run: dotnet restore

      # Executar testes e gerar cobertura
      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      # Converter cobertura para formato compatível com SonarCloud
      - name: Convert coverage to OpenCover format
        run: |
          reportgenerator \
            -reports:./TestResults/**/*.xml \
            -targetdir:./TestResults/coverage \
            -reporttypes:Opencover

      # Baixar o scanner do SonarCloud
      - name: Download SonarCloud Scanner
        uses: sonarsource/sonarcloud-github-action@v2

      # Executar análise no SonarCloud
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
