name: SonarCloud

on:
  push:
    branches:
      - master
      - branch-**
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Cache Dotnet Coverage
        id: cache-dotnet-coverage
        uses: actions/cache@v4
        with:
          path: .\.sonar\coverage
          key: ${{ runner.os }}-dotnet-coverage
          restore-keys: ${{ runner.os }}-dotnet-coverage

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Install Dotnet Coverage
        if: steps.cache-dotnet-coverage.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\coverage -ItemType Directory
          dotnet tool install dotnet-coverage --tool-path .\.sonar\coverage

      - name: Restore dependencies
        shell: powershell
        run: |
          dotnet restore ./SampleWebApi.sln

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"Viniciusmendes21_API_Iquirium" `
            /o:"viniciusmendes21" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.cs.opencover.reportsPaths="./TestResults/coverage.opencover.xml" `
            /d:sonar.coverage.exclusions="**/Migrations/**"
          dotnet build ./SampleWebApi.sln
          dotnet test ./SampleWebApi.sln `
            --collect:"XPlat Code Coverage;Format=cobertura,opencover" `
            --results-directory "./TestResults"

      - name: Verify Coverage File
        shell: bash
        run: |
          echo "Verifying coverage.opencover.xml..."
          if [ ! -f "./TestResults/coverage.opencover.xml" ]; then
            echo "Coverage file not found!"
            exit 1
          else
            echo "Coverage file found!"
          fi

      - name: Complete SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
